---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings

language: en-US
backgroundOpacity: 0.6
headerStyle: underlined
cardBlur: md
statusStyle: 'dot'
showStats: true

background:
  image: /images/tokyo-night.jpg
  brightness: 75

layout:
  Media:
    style: row
    columns: 3
  Finder:
  Dashboard:
  Configuration:
  Tools:
    style: row
    columns: 2

providers:
  # openweathermap: apikeyhere
